apiVersion: v1
kind: Service
metadata:
  name: dunno-service
  labels:
    app: dunno
spec:
  selector:
    app: dunno
  ports:
    - protocol: TCP
      port: 3000 # Service port
      targetPort: 3000 # Container port
  type: NodePort # change to LoadBalancer if running in cloud